import { FeeManagementData } from "@/@core/store/feeManagementStore";

export const newFee = {
  code: 200,
  data: {
    customerName: "AIZENSHTAT YESHAYAHU",
    customerAddress: "YESHAYAHU AIZENSHTAT",
    customerAccountOfficer: "039 Melissa Scotti           BR 13",
    cif: "AAA0140",
    fees: [
      {
        feeType: "Customer Fees",
        feeGroups: [
          {
            visible: true,
            name: "Standard Fees",
            code: 1,
            fields: [
              {
                hasChanged: false,
                code: 1,
                isException: false,
                name: "Account Maintenance",
                defaultValue: "1200",
                exceptionOptions: [],
                createdAt: "2023-05-20T16:25:31.435Z",
                updatedAt: "2023-05-20T16:25:31.435Z",
                isCurrentClient: false,
                isStandard: true,
                id: "6468f46eff51aa9d77d849d7",
                labelValue: "$1,200.00",
              },
              {
                hasChanged: false,
                code: 2,
                isException: false,
                name: "Hold Mail",
                defaultValue: "600",
                exceptionOptions: [],
                createdAt: "2023-05-20T16:25:31.435Z",
                updatedAt: "2023-05-20T16:25:31.435Z",
                isCurrentClient: false,
                isStandard: true,
                id: "6468f46eff51aa9d77d849d8",
                labelValue: "$600.00",
              },
            ],
            id: "649a04fac7f9cb1cedc48eb4",
            cif: "AAA0140",
            accountNumber: 6037828,
          },
          {
            visible: true,
            name: "Client Current Fees",
            code: 1,
            fields: [
              {
                hasChanged: false,
                code: 1,
                isException: false,
                name: "Account Maintenance",
                defaultValue: "0",
                exceptionOptions: [],
                createdAt: "2023-05-20T16:25:31.436Z",
                updatedAt: "2023-05-20T16:25:31.436Z",
                isCurrentClient: true,
                isStandard: false,
                id: "6468f46eff51aa9d77d849dc",
                labelValue: "$0.00",
              },
              {
                hasChanged: false,
                code: 2,
                isException: false,
                name: "Hold Mail ",
                defaultValue: "0",
                exceptionOptions: [],
                createdAt: "2023-05-20T16:25:31.436Z",
                updatedAt: "2023-05-20T16:25:31.436Z",
                isCurrentClient: true,
                isStandard: false,
                id: "6468f46eff51aa9d77d849dd",
                labelValue: "$0.00",
              },
            ],
            id: "649a04fac7f9cb1cedc48eb7",
            cif: "AAA0140",
            accountNumber: 6037828,
          },
          {
            visible: true,
            name: "Exception Request",
            code: 1,
            fields: [
              {
                hasChanged: false,
                code: 1,
                isException: true,
                name: "Account Maintenance",
                defaultValue: "",
                exceptionOptions: [
                  {
                    value: "1200",
                    text: "$1,200.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d849e2",
                    parameterOptionId: 11,
                  },
                  {
                    value: "0",
                    text: "$0.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d849e3",
                    parameterOptionId: 12,
                  },
                ],
                createdAt: "2023-05-20T16:25:31.436Z",
                updatedAt: "2023-05-20T16:25:31.436Z",
                isCurrentClient: false,
                isStandard: false,
                id: "6468f46eff51aa9d77d849e1",
                labelValue: "$0.00",
              },
              {
                hasChanged: false,
                code: 2,
                isException: true,
                name: "Hold Mail ",
                defaultValue: "",
                exceptionOptions: [
                  {
                    value: "600",
                    text: "$600",
                    visible: true,
                    _id: "6468f46eff51aa9d77d849e5",
                    parameterOptionId: 13,
                  },
                  {
                    value: "0",
                    text: "$0.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d849e6",
                    parameterOptionId: 14,
                  },
                ],
                createdAt: "2023-05-20T16:25:31.436Z",
                updatedAt: "2023-05-20T16:25:31.436Z",
                isCurrentClient: false,
                isStandard: false,
                id: "6468f46eff51aa9d77d849e4",
                labelValue: "$0.00",
              },
            ],
            id: "649a04fac7f9cb1cedc48eba",
            cif: "AAA0140",
            accountNumber: 6037828,
          },
        ],
        id: "6468f46eff51aa9d77d849ee",
      },
      {
        feeType: "Bank Account Fees",
        feeGroups: [
          {
            name: "Standard Fees",
            code: 2,
            fields: [
              {
                code: 3,
                isStandard: true,
                isCurrentClient: false,
                isException: false,
                name: "Incoming Wire",
                defaultValue: "10",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f1c",
                createdAt: "2023-05-20T16:25:31.436Z",
                updatedAt: "2023-05-20T16:25:31.436Z",
                labelValue: "$10.00",
              },
              {
                code: 4,
                isStandard: true,
                isCurrentClient: false,
                isException: false,
                name: "Outgoing Wire",
                defaultValue: "75",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f1d",
                createdAt: "2023-05-20T16:25:31.436Z",
                updatedAt: "2023-05-20T16:25:31.436Z",
                labelValue: "$75.00",
              },
            ],
            cif: "AAA0140",
            accountNumber: "6037828",
            visible: true,
            _id: "649a04fac7f9cb1cedc48f1b",
          },
          {
            name: "Client Current Fees",
            code: 2,
            fields: [
              {
                code: 3,
                isStandard: false,
                isCurrentClient: true,
                isException: false,
                name: "Incoming Wire",
                defaultValue: "0",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f1f",
                createdAt: "2023-05-20T16:25:31.437Z",
                updatedAt: "2023-05-20T16:25:31.437Z",
                labelValue: "$0.00",
              },
              {
                code: 4,
                isStandard: false,
                isCurrentClient: true,
                isException: false,
                name: "Outgoing Wire",
                defaultValue: "0",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f20",
                createdAt: "2023-05-20T16:25:31.437Z",
                updatedAt: "2023-05-20T16:25:31.437Z",
                labelValue: "$0.00",
              },
            ],
            cif: "AAA0140",
            accountNumber: "6037828",
            visible: true,
            _id: "649a04fac7f9cb1cedc48f1e",
          },
          {
            name: "Exception Request",
            code: 2,
            fields: [
              {
                code: 3,
                isStandard: false,
                isCurrentClient: false,
                isException: true,
                name: "Incoming Wire",
                defaultValue: "0",
                hasChanged: false,
                exceptionOptions: [
                  {
                    value: "10",
                    text: "$10.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a07",
                  },
                  {
                    value: "0",
                    text: "0.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a08",
                  },
                ],
                _id: "649a04fac7f9cb1cedc48f22",
                createdAt: "2023-05-20T16:25:31.437Z",
                updatedAt: "2023-05-20T16:25:31.437Z",
                labelValue: "$0.00",
              },
              {
                code: 4,
                isStandard: false,
                isCurrentClient: false,
                isException: true,
                name: "Outgoing Wire",
                defaultValue: "0",
                hasChanged: false,
                exceptionOptions: [
                  {
                    value: "75",
                    text: "$75.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a0a",
                  },
                  {
                    value: "60",
                    text: "$60.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a0b",
                  },
                  {
                    value: "50",
                    text: "$50.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a0c",
                  },
                  {
                    value: "30",
                    text: "$30.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a0d",
                  },
                  {
                    value: "20",
                    text: "$20.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a0e",
                  },
                  {
                    value: "10",
                    text: "$10.00",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a0f",
                  },
                ],
                _id: "649a04fac7f9cb1cedc48f25",
                createdAt: "2023-05-20T16:25:31.437Z",
                updatedAt: "2023-05-20T16:25:31.437Z",
                labelValue: "$0.00",
              },
            ],
            cif: "AAA0140",
            accountNumber: "6037828",
            visible: true,
            _id: "649a04fac7f9cb1cedc48f21",
          },
        ],
        id: "6468f46eff51aa9d77d84a1b",
      },
      {
        feeType: "Investiment Account Fees",
        feeGroups: [
          {
            name: "Standard Fees",
            code: 3,
            fields: [
              {
                code: 6,
                isStandard: true,
                isCurrentClient: false,
                isException: false,
                name: "Safekeeping-Custoty",
                defaultValue: "A021",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f4b",
                createdAt: "2023-05-20T16:25:31.437Z",
                updatedAt: "2023-05-20T16:25:31.437Z",
                labelValue: "A021 - A021 - 0.35% per year with a minimum of $375.00 per quarter",
              },
              {
                code: 7,
                isStandard: true,
                isCurrentClient: false,
                isException: false,
                name: "Equity and Options Commission",
                defaultValue: "E3",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f4c",
                createdAt: "2023-05-20T16:25:31.438Z",
                updatedAt: "2023-05-20T16:25:31.438Z",
                labelValue: "E3 - E3 - Equity:$0.10 per share, with a minimum charge of $150 per trade; Option:$0.05 per share, with a minimum charge of $150 per trade",
              },
            ],
            cif: "AAA0140",
            accountNumber: "20001769",
            entityCode: "SNB/284",
            visible: true,
            _id: "649a04fac7f9cb1cedc48f4a",
          },
          {
            name: "Client Current Fees",
            code: 3,
            fields: [
              {
                code: 6,
                isStandard: false,
                isCurrentClient: true,
                isException: false,
                name: "Safekeeping-Custoty",
                defaultValue: "F100",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f4e",
                createdAt: "2023-05-20T16:25:31.438Z",
                updatedAt: "2023-05-20T16:25:31.438Z",
                labelValue: "F100 - F100 - Waived Custody Fee",
              },
              {
                code: 7,
                isStandard: false,
                isCurrentClient: true,
                isException: false,
                name: "Equity and Options Commission",
                defaultValue: "E3",
                hasChanged: false,
                exceptionOptions: [],
                _id: "649a04fac7f9cb1cedc48f4f",
                createdAt: "2023-05-20T16:25:31.438Z",
                updatedAt: "2023-05-20T16:25:31.438Z",
                labelValue: "E3 - E3 - Equity:$0.10 per share, with a minimum charge of $150 per trade; Option:$0.05 per share, with a minimum charge of $150 per trade",
              },
            ],
            cif: "AAA0140",
            accountNumber: "20001769",
            entityCode: "SNB/284",
            visible: true,
            _id: "649a04fac7f9cb1cedc48f4d",
          },
          {
            name: "Exception Request",
            code: 3,
            fields: [
              {
                code: 6,
                isStandard: false,
                isCurrentClient: false,
                isException: true,
                name: "Safekeeping-Custoty",
                defaultValue: "0",
                hasChanged: false,
                exceptionOptions: [
                  {
                    value: "A032",
                    text: "A032 - 0.50% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48edc",
                  },
                  {
                    value: "A101",
                    text: "A101 - 0.50% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48edd",
                  },
                  {
                    value: "A102",
                    text: "A102 - 0.50% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ede",
                  },
                  {
                    value: "A031",
                    text: "A031 - 0.45% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48edf",
                  },
                  {
                    value: "A103",
                    text: "A103 - 0.45% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee0",
                  },
                  {
                    value: "A104",
                    text: "A104 - 0.45% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee1",
                  },
                  {
                    value: "A030",
                    text: "A030 - 0.40% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee2",
                  },
                  {
                    value: "A105",
                    text: "A105 - 0.40% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee3",
                  },
                  {
                    value: "A106",
                    text: "A106 - 0.40% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee4",
                  },
                  {
                    value: "A021",
                    text: "A021 - 0.35% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee5",
                  },
                  {
                    value: "A107",
                    text: "A107 - 0.35% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee6",
                  },
                  {
                    value: "A108",
                    text: "A108 - 0.35% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee7",
                  },
                  {
                    value: "A001",
                    text: "A001 - 0.30% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee8",
                  },
                  {
                    value: "A109",
                    text: "A109 - 0.30% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ee9",
                  },
                  {
                    value: "A110",
                    text: "A110 - 0.30% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48eea",
                  },
                  {
                    value: "A022",
                    text: "A022 - 0.25% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48eeb",
                  },
                  {
                    value: "A068",
                    text: "A068 - 0.25% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48eec",
                  },
                  {
                    value: "A088",
                    text: "A088 - 0.25% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48eed",
                  },
                  {
                    value: "A053",
                    text: "A053 - 0.20% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48eee",
                  },
                  {
                    value: "A070",
                    text: "A070 - 0.20% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48eef",
                  },
                  {
                    value: "A111",
                    text: "A111 - 0.20% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef0",
                  },
                  {
                    value: "A089",
                    text: "A089 - 0.15% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef1",
                  },
                  {
                    value: "A012",
                    text: "A012 - 0.15% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef2",
                  },
                  {
                    value: "A073",
                    text: "A073 - 0.15% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef3",
                  },
                  {
                    value: "A071",
                    text: "A071 - 0.10% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef4",
                  },
                  {
                    value: "A008",
                    text: "A008 - 0.10% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef5",
                  },
                  {
                    value: "A112",
                    text: "A112 - 0.10% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef6",
                  },
                  {
                    value: "A113",
                    text: "A113 - 0.05% per year with a minimum of $375.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef7",
                  },
                  {
                    value: "A009",
                    text: "A009 - 0.05% per year with a minimum of $250.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef8",
                  },
                  {
                    value: "A114",
                    text: "A114 - 0.05% per year with a minimum of $125.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48ef9",
                  },
                  {
                    value: "A115",
                    text: "A115 - 0.50% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48efa",
                  },
                  {
                    value: "A116",
                    text: "A116 - 0.45% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48efb",
                  },
                  {
                    value: "A117",
                    text: "A117 - 0.30% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48efc",
                  },
                  {
                    value: "A118",
                    text: "A118 - 0.25% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48efd",
                  },
                  {
                    value: "A119",
                    text: "A119 - 0.20% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48efe",
                  },
                  {
                    value: "A025",
                    text: "A025 - 0.15% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48eff",
                  },
                  {
                    value: "A023",
                    text: "A023 - 0.10% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f00",
                  },
                  {
                    value: "A120",
                    text: "A120 - 0.05% per year with a minimum of $100.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f01",
                  },
                  {
                    value: "A121",
                    text: "A121 - 0.50% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f02",
                  },
                  {
                    value: "A122",
                    text: "A122 - 0.45% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f03",
                  },
                  {
                    value: "A123",
                    text: "A123 - 0.30% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f04",
                  },
                  {
                    value: "A124",
                    text: "A124 - 0.25% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f05",
                  },
                  {
                    value: "A125",
                    text: "A125 - 0.20% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f06",
                  },
                  {
                    value: "A126",
                    text: "A126 - 0.15% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f07",
                  },
                  {
                    value: "A127",
                    text: "A127 - 0.10% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f08",
                  },
                  {
                    value: "A128",
                    text: "A128 - 0.05% per year with a minimum of $75.00 per quarter",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f09",
                  },
                  {
                    value: "F100",
                    text: "F100 - Waived Custody Fee",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f0a",
                  },
                  {
                    value: "F017",
                    text: "F017 - Flat Quarterly Custody Fee $ 2500",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f0b",
                  },
                  {
                    value: "F108",
                    text: "F108 - Flat Quarterly Custody Fee $ 1500",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f0c",
                  },
                  {
                    value: "F009",
                    text: "F009 - Flat Quarterly Custody Fee $ 1000",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f0d",
                  },
                  {
                    value: "F002",
                    text: "F002 - Flat Quarterly Custody Fee $ 500",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f0e",
                  },
                ],
                _id: "649a04fac7f9cb1cedc48f51",
                createdAt: "2023-05-20T16:25:31.438Z",
                updatedAt: "2023-05-20T16:25:31.438Z",
                labelValue: "F100 - F100 - Waived Custody Fee",
              },
              {
                code: 7,
                isStandard: false,
                isCurrentClient: false,
                isException: true,
                name: "Equity and Options Commission",
                defaultValue: "0",
                hasChanged: false,
                exceptionOptions: [
                  {
                    value: "B6",
                    text: "B6 - Equity:$0.03 per share, with a minimum charge of $150 per trade; Option:$0.03 per share, with a minimum charge of $150 per trade",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a41",
                  },
                  {
                    value: "C8",
                    text: "C8 - Equity:$0.05 per share, with a minimum charge of $100 per trade; Option:$0.05 per share, with a minimum charge of $100 per trade",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a42",
                  },
                  {
                    value: "D2",
                    text: "D2 - Equity:$0.05 per share, with a minimum charge of $150 per trade; Option:$0.05 per share, with a minimum charge of $150 per trade",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a43",
                  },
                  {
                    value: "D7",
                    text: "D7 - Equity:$0.07 per share, with a minimum charge of $150 per trade; Option:$0.05 per share, with a minimum charge of $150 per trade",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a44",
                  },
                  {
                    value: "E3",
                    text: "E3 - Equity:$0.10 per share, with a minimum charge of $150 per trade; Option:$0.05 per share, with a minimum charge of $150 per trade",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a45",
                  },
                  {
                    value: "I3",
                    text: "I3 - Equity:100 basis points, with a minimum charge of $150 per trade; Option:100 basis points, with a minimum charge of $150 per trade",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a46",
                  },
                  {
                    value: "I8",
                    text: "I8 - Equity:$0.03 per share, with a minimum charge of $100 per trade; Option:$0.03 per share, with a minimum charge of $100 per trade",
                    visible: true,
                    _id: "6468f46eff51aa9d77d84a47",
                  },
                  {
                    value: "",
                    text: "Other",
                    visible: true,
                    _id: "649a04fac7f9cb1cedc48f1a",
                  },
                ],
                _id: "649a04fac7f9cb1cedc48f85",
                createdAt: "2023-05-20T16:25:31.438Z",
                updatedAt: "2023-05-20T16:25:31.438Z",
                labelValue: "E3 - E3 - Equity:$0.10 per share, with a minimum charge of $150 per trade; Option:$0.05 per share, with a minimum charge of $150 per trade",
              },
            ],
            cif: "AAA0140",
            accountNumber: "20001769",
            entityCode: "SNB/284",
            visible: true,
            _id: "649a04fac7f9cb1cedc48f50",
          },
        ],
        id: "6468f46eff51aa9d77d84a56",
      },
    ],
    feesActives: [],
    documentUrl: "https://minio-ui.dev.k8s.safra.int/api/v1/buckets/jarvis-public/objects/download?preview=true&prefix=U2NoZWR1bGVPZkZlZXMucGRm",
    currentFees: [
      {
        ddaNumber: 6037828,
        bpsAcctNumber: "",
        feeDescription: "AccountMaintenance",
        entity: "SNB/284",
        feeCode: "JH001",
        feeAmmount: 0,
      },
      {
        ddaNumber: 6037828,
        bpsAcctNumber: "",
        feeDescription: "HoldMail",
        entity: "SNB/284",
        feeCode: "JH002",
        feeAmmount: 0,
      },
      {
        ddaNumber: 6037828,
        bpsAcctNumber: "",
        feeDescription: "USD/FXIncomingWire",
        entity: "SNB/284",
        feeCode: "JH010",
        feeAmmount: 0,
      },
      {
        ddaNumber: 6037828,
        bpsAcctNumber: "",
        feeDescription: "USD/FXOutgoingWire",
        entity: "SNB/284",
        feeCode: "JH008",
        feeAmmount: 0,
      },
      {
        ddaNumber: 6037828,
        bpsAcctNumber: "20001769",
        feeDescription: "SafekeepingCustody",
        entity: "SNB/284",
        feeCode: "F100",
        feeAmmount: 0,
      },
      {
        ddaNumber: 6037828,
        bpsAcctNumber: "20001769",
        feeDescription: "EquityCommissions",
        entity: "SNB/284",
        feeCode: "E3",
        feeAmmount: 0,
      },
      {
        ddaNumber: 6037828,
        bpsAcctNumber: "20001769",
        feeDescription: "OptionsCommissions",
        entity: "SNB/284",
        feeCode: "E3",
        feeAmmount: 0,
      },
    ],
  },
} as unknown as FeeManagementData
